name: video_call
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  agora_rtc_engine: ^6.3.0
  agora_uikit: ^1.3.8
  permission_handler: ^11.3.0
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/img/

  fonts:
    - family: NotoSans
      fonts:
        - asset: asset/font/NotoSansKR-Black.otf
          weight: 900
        - asset: asset/font/NotoSansKR-Bold.otf
          weight: 700
        - asset: asset/font/NotoSansKR-Medium.otf
          weight: 500
        - asset: asset/font/NotoSansKR-Regular.otf
          weight: 400
        - asset: asset/font/NotoSansKR-Light.otf
          weight: 300
        - asset: asset/font/NotoSansKR-Thin.otf
          weight: 100
